config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  resources :actors

  resources :movies, except: [:destroy]

  namespace :api do
    resources :movies, defaults: { :format => 'json'}
    resources :actors, defaults: { :format => 'json'}
  end

  devise_for :users

  root 'home#index'

  resource :profile, except: [:destroy]

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews
  has_and_belongs_to_many :actors
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :review
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_actor, only: [:show, :edit, :update]

  def index
    @actors = Actor.all
  end

  def edit
  end

  def show
  end

  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.new(actor_params)
    if @actor.save
      redirect_to @actor
    else
      render :index
    end
  end

  private

  def set_actor
    @actor = Actor.find(params[:id])
  end

  def actor_params
    params.require(:actor).permit(:name, :year_of_birth, :thumbnail)
  end

end

app/controllers/api/actors_controller.rb
module Api
  class ActorsController < ApplicationController

    protect_from_forgery with: :null_session

    def index
      render json: Actor.all
    end

    def show
      render json: Actor.find(params[:id])
    end

    def create
      actor = Actor.new(actor_params)
      if actor.save
        render json: actor, status: 201, location: [:api, actor]
      else
        render json: actor.errors, status: 422
      end
    end

    def update
      actor = Actor.find(params[:id])
      if actor.update(actor)
        head 204
      else
        render json: actor.error, status: 422
      end
    end

    def destroy
      actor = Actor.find(params[:id])
      actor.destroy
      head 204
    end

    private

    def actor_params
      params.require(:actor).permit(:name, :year_of_birth, :thumbnail)
    end

  end
end

app/controllers/api/movies_controller.rb
module Api
  class MoviesController < ApplicationController

    protect_from_forgery with: :null_session

    def index
      render json: Movie.all
    end

    def show
      render json: Movie.find(params[:id])
    end

    def create
      movie = Movie.new(movie_params)
      if movie.save
        render json: movie, status: 201, location: [:api, movie]
      else
        render json: movie.errors, status: 422
      end
    end

    def update
      movie = Movie.find(params[:id])
      if movie.update(movie)
        head 204
      else
        render json: movie.error, status: 422
      end
    end

    def destroy
      movie = Movie.find(params[:id])
      movie.destroy
      head 204
    end

    private

    def movie_params
      params.require(:movie).permit(:title, :summary, :youtube_embed_link, :thumbnail)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    root_path
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: [:show, :edit, :update]

  def edit
  end

  def update
    if @movie.update_attributes(movie_params)
      redirect_to @movie
    else
      render :edit
    end
  end

  def show
    @review = Review.where(movie_id: @movie)
  end

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie
    else
      render :index
    end
  end



  private

  def movie_params
    params.require(:movie).permit(:title, :summary, :youtube_embed_link, :thumbnail, actor_ids: [])
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update]

  def show
  end

  def new
    @profile = current_user.build_profile
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update_attributes(profile_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

    def profile_params
      params.require(:profile).permit(:name)
    end



  def set_profile
    @profile = current_user.profile
    if !@profile
      redirect_to new_profile_path and return
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update]


  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def edit
  end

  def show
  end

  def create
      @review = Review.new(review_params)
    if @review.save
      redirect_to @review
    else
      render :index
    end
  end

  def destroy
  end

  def update
    if @review.update_attributes(review_params)
      redirect_to @review
    else
      render :edit
    end
  end

  private

  def review_params
    params.require(:review).permit(:body, :movie_id, :user_id)
  end


end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/actors/_form.html.erb
<%= form_for @actor do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :year_of_birth %>
    <%= f.text_field :year_of_birth %>
  </p>
  <p>
    <%= f.label :thumbnail %>
    <%= f.text_field :thumbnail %>
  </p>

  <%= f.submit %>
<% end %>

app/views/actors/edit.html.erb
<h1>Edit an Actor</h1>

<%= render 'form' %>

app/views/actors/index.html.erb
<h1>Actors</h1>

<%= link_to "Add New Actor", new_actor_path %>
<br> <br>

<table>
  <thead>
    <tr>
      <th>Thumbnail</th>
      <th>Name</th>
      <th>Year of Birth</th>
    </tr>
  </thead>
  <tbody>
    <% @actors.each do |actor|%>
    <tr>
      <td><img width=100 src=<%= actor.thumbnail %>></td>
      <td><%= link_to actor.name, actor %></td>
      <td><%= actor.year_of_birth %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<br><br>
  <%= link_to "Movies", movies_path %>

app/views/actors/new.html.erb
<h1>Add an Actor</h1>

<%= render 'form' %>

app/views/actors/show.html.erb
<h1><%= @actor.name %></h1>

<h2>Born: <%= @actor.year_of_birth %></h2>

<p><img height=200 src=<%= @actor.thumbnail %>></p>



<% @actor.movies.each do |movie| %>
  <p><h4>Movies: </h4><%= link_to movie.title, movie_path(movie) %></p>
<% end %>

<%= link_to "Edit", edit_actor_path %> |
<%= link_to "Show All Actors", actors_path %>

app/views/home/index.html.erb
<h1>IMDB CLONE</h1>

<% if !current_user %>
  <div class='log-in-buttons'>
    <h2>New Users!</h2>

    <button> <%= link_to "Sign Up", new_user_registration_path %> </button>
    <br>
    <h2>Existing Users!</h2>
    <button> <%= link_to "Log In", new_user_session_path %> </button>

  <% else %>
    <%= link_to "Movies", movies_path %> |
    <%= link_to "Actors", actors_path %>
    <br> <br>

    <button> <%= link_to "Log Out", destroy_user_session_path, method: :delete %> </button>


  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IMDB CLONE</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :summary %>
    <%= f.text_field :summary %>
  </p>
  <p>
    <%= f.label :youtube_embed_link %>
    <%= f.text_field :youtube_embed_link %>
  </p>
  <p>
    <%= f.label :thumbnail %>
    <%= f.text_field :thumbnail %>
  </p>
  <p>Add starring actors already in our database:</p>
  <% Actor.all.each do |actor| %>
  <%= check_box_tag 'movie[actor_ids][]', actor.id %> <%= actor.name %>
  <br><br>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Movies</h1>

<%= link_to "Add New Movie", new_movie_path %>
<br> <br>

<table>
  <thead>
    <tr>
      <th>Thumbnail</th>
      <th>Title</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie|%>
    <tr>
      <td><img width=50 src=<%= movie.thumbnail %>></td>
      <td><%= link_to movie.title, movie %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<br><br>
<%= link_to "Actors", actors_path %>

app/views/movies/new.html.erb
<h1>Add Movie</h1>

<%= render 'form' %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<div><%= @movie.youtube_embed_link.html_safe %></div>

<p><%= @movie.summary %></p>

<% @movie.actors.each do |actor| %>
<p><%= link_to actor.name, actor_path(actor) %></p>
<% end %>

<%= link_to "Edit", edit_movie_path %> |
<%= link_to "Show All Movies", movies_path %>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: profile_path do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <%= f.submit %>
<% end %>

app/views/profiles/edit.html.erb
<h2>Edit Profile</h2>

<%= render 'form' %>

app/views/profiles/new.html.erb
<h2>Create your profile</h2>

<%= render 'form' %>

app/views/profiles/show.html.erb
<%= current_user.email %>

<%= link_to "Edit Profile", edit_profile_path %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>